path_prefix: './'

# MODELS
full_model: 'language'
full_models: ['language']

# DATA
ds_max_len: 32
ds_max_lens: [24, 32]
max_len: 128

# TRAINING
epochs: 100
batch_size: 16
lang_encoder_lr: 0.001
lang_decoder_lr: 0.001
label_smoothing: 0.0001
