# LOGGING AND LOGISTICS
local_prefix: ./
run_name: local_optim_test
use_gcs: true
gcs_prefix: gs://code-glyphs/
s3_bucket: gestalt-graph
gcs_bucket: code-glyphs
img_summaries_per_epoch: 4
img_summaries_every_n_epochs: 5

# MODELS
full_model: vision
full_models: [language, vision, gestalt]
eager_mode: false

# -- LANGUAGE
lang_autoencoder_r: 4 # 48x48
language_model_size: 768

# -- VISION
vision_model_size: 2048
# -- -- CPPN
img_dim: 128
generator_levels: 5
res_blocks_per_level: 4
c_out: 8
composite_colors:
  - "ff0000" # primary
  - "00ff00"
  - "0000ff"
  - "ffff00" # secondary
  - "00ffff"
  - "ff00ff"
  - "ffffff" # bw
  - "000000"

# DATA
max_len: 48
num_symbols: 64

# TRAINING
epochs: 500
batch_size: 4
lang_encoder_lr: 1.e-6 # BERT: peak value of 1-e4 with b=256
lang_decoder_lr: 5.e-7
generator_lr: 5.e-5
decoder_lr: 5.e-5
default_lr: 5.e-5
label_smoothing: 0.0005
use_aug: true

# learning rate scheduling
use_warmup: true
warmup_steps: 1000
use_decay: true
decay_rate: 0.96
decay_steps: 1000
