path_prefix: './'

# MODELS
full_model: 'language'
full_models: ['language']
eager_mode: false

# -- LANGUAGE
lang_autoencoder_r: 4 # 48x48
language_model_size: 768

# -- VISION
vision_hidden_size: 512
# -- -- CPPN
img_dim: 256
cppn_layers: 5
c_out: 5
composite_colors:
  - "ffffff"
  - "000000"
  - "cc9900"
  - "00bbcc"
  - "63cc00"

# DATA
max_len: 48

# TRAINING
epochs: 100
batch_size: 8
lang_encoder_lr: 1.e-4 # BERT: peak value of 1-e4 with b=256
lang_decoder_lr: 1.e-4
label_smoothing: 0.00001
